---
title: "Lab 6: Quarto Presentation"
author: "Sara Hussin"
format: revealjs
editor: visual
bibliography: references.bib
---

## Some Important Literature

-   [@moutafi_discovery_2022] talks about the discovery of biomarkers for non-small cell lung cancer using spatial profiling. In a project, we tried to do the same, but using elastic net regression.

-   There are issues with expressing NEK proteins in *E. coli* and after reading through the literature, we decided to implement a certain mutation that we hypothesized would help with expression [@rellos_structure_2007].

-   I've become more interested in ML for drug discovery. [@catacutan_machine_2024] talks about the different applications of machine learning in this area and how it can significantly improve clinical translation and patient outcomes.

## A Cool Equation or Two

-   The equation that made me fall in love with calculus and mathematics

$$
f'(x) = \lim_{h \rightarrow 0} \frac{f(x+h)-f(x)}{h}
$$

-   A system of linear equations that are rewritten in an augmented matrix in order to begin finding a solution (not sure if a solution actually exists)

    $$
    \begin{cases} 3x+5y+z = 1 \\ 7x-2y+4z = 2 \\ -6x+3y+2z = 3
    \end{cases} \Rightarrow
    A =
    \begin{bmatrix}
     3&5&1&1 \\
     7&-2&4&2 \\
     -6&3&2&3
    \end{bmatrix}
    $$

## References
